---
- hosts: all
  vars:
  - warName: helloworld.war
  - warRemotePath: /opt/apache-tomcat-8.5.30/webapps

  tasks:
  - name: Copy WAR to server
    copy: src=/var/lib/jenkins/workspace/Ansible/target/java-example.war dest={{ warRemotePath }}/{{ warName }} remote_src=yes
    
